---
services:
  nodered:
    image: ghcr.io/chukysoria/nodered:v1.4.27@sha256:4c80bd22c2df1fcf3b8ce8039a3bb83c974ab9af3561a09877b2e97f8a673cb1
    container_name: nodered
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      # Node-Red
      NPM_PACKAGES: "node-red-contrib-alexa-smart-home passport-openidconnect"
    networks:
      - frontend
      - nodered-backend-net
    volumes:
      - ${BASE_PATH:-/volume2/docker/}nodered:/config:rw
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.routers.nodered-rtr.rule: Host(`nodered.${DOMAIN:-boulebar.duckdns.org}`)

networks:
  frontend:
    external: true # Defined in portainer
  nodered-backend-net:
    external: true # Defined in base
