---
services:
  nodered:
    image: ghcr.io/chukysoria/nodered:v1.4.26@sha256:422eb30f5837cd4c05bbd41506e379527ca7b2b43bfad2e6d077a996fea6b298
    container_name: nodered
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      # Node-Red
      NPM_PACKAGES: "node-red-contrib-alexa-smart-home passport-openidconnect"
    networks:
      - frontend
      - nodered-backend-net
    volumes:
      - ${BASE_PATH:-/volume2/docker/}nodered:/config:rw
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.routers.nodered-rtr.rule: Host(`nodered.${DOMAIN:-boulebar.duckdns.org}`)

networks:
  frontend:
    external: true # Defined in portainer
  nodered-backend-net:
    external: true # Defined in base
