---
services:
  postgresql:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      -  ${BASE_PATH:-/volume2/docker/}databases/postgresql:/var/lib/postgresql/data
    networks:
      - database
      - authentik
    environment:
      TZ: ${TZ:-Europe/Madrid}      
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_DB: ${PG_DB:-authentik}

  timescale-db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped    
    volumes:
      - ${BASE_PATH:-/volume2/docker/}databases/timescaledb:/var/lib/postgresql/data
    networks:
      - database
      - homeassistant
    environment:
      TZ: ${TZ:-Europe/Madrid}
      POSTGRES_USER: ${TS_USER:-homeassistant}
      POSTGRES_PASSWORD: ${TS_PASS:?database password required}
      POSTGRES_DB: ${TS_DB:-homeassistant}      

  redis:
    image: redis:alpine
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ${BASE_PATH:-/volume2/docker/}databases/redis:/data:uid=${PUID:-1029},gid=${PGID:-65536}
    networks:
      - database
      - authentik

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?PGAdmin password required}
    volumes:
      - pgadmin:/var/lib/pgadmin:uid
    networks:
      - frontend
      - database
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.routers.pgadmin-rtr.rule: Host(`pgadmin.${DOMAIN:-boulebar.duckdns.org}`)

networks:
  authentik:
    name: authentik
    ipam:
      driver: default
      config:
        - subnet: 172.19.2.0/24
          gateway: 172.19.2.1
  database:
    name: database
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
  frontend:
    external: true # Defined in postgres
  homeassistant:
    name: homeassistant
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
          gateway: 172.19.1.1

volumes:
  pgadmin:
