---
services:
  timescale-db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale-db
    restart: unless-stopped    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ${BASE_PATH:-/volume2/docker/}databases/timescaledb:/var/lib/postgresql/data
    environment:
      TZ: Europe/Madrid
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${PG_DB:-homeassistant}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
    networks:
      - database
      - homeassistant

  redis:
    image: redis:alpine
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - database
      - authentik

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?PGAdmin password required}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - frontend
      - database
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.authentik-rtr.rule: Host(`pgadmin.${DOMAIN:-boulebar.duckdns.org}`)

networks:
  authentik:
    name: authentik
    ipam:
      driver: default
      config:
        - subnet: 172.19.2.0/24
          gateway: 172.19.2.1
  database:
    name: database
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
  frontend:
    name: frontend
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  homeassistant:
    name: homeassistant
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
          gateway: 172.19.1.1

volumes:
  redis:
  pgadmin:
