services:
  importer:
    image: fireflyiii/data-importer:version-2.3.2@sha256:4e2cbcb0d95c34850534a3772f1732c00f6412077db33b1863703a1b628bdc12
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    env_file:
      - ../../stack.env
    networks:
      - firefly-net
      - firefly-frontend-net
      - firefly-db-net
    volumes:
      - ${BASE_PATH:-/volume2/docker/}firefly/import:/import:rw
    labels:
      traefik.enable: true
      traefik.docker.network: firefly-frontend-net
      traefik.http.routers.firefly-importer-rtr.rule: Host(`ffimporter.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.firefly-importer-rtr.middlewares: authentik@docker

networks:
  firefly-net:
    external: true # Defined in base
  firefly-frontend-net:
    external: true # Defined in base
  firefly-db-net:
    external: true # Defined in base
