services:
  app:
    image: fireflyiii/core:latest@sha256:8391c11f3260354a1feb48d1cf2cb822ad00db311efe2b21eccd7d5ee6bfe60a
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly-net
      - firefly-net-frontend
      - firefly-db-net
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      traefik.enable: true
      traefik.docker.network: firefly-net-frontend
      traefik.http.routers.fireflyiii-rtr.rule: Host(`firefly.${DOMAIN:-boulebar.duckdns.org}`)

  importer:
    image: fireflyiii/data-importer:latest@sha256:6dae0dd6f415d4cbc1a858533fced215aee50fcf69c39645f2b80ef1616db612
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly-net
      - firefly-net-frontend 
      - firefly-db-net   
    depends_on:
      - app
    env_file: .importer.env
    labels:
      traefik.enable: true
      traefik.docker.network: firefly-net-frontend
      traefik.http.routers.firefly-importer-rtr.rule: Host(`ffimporter.${DOMAIN:-boulebar.duckdns.org}`)

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine:latest@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ:-Europe/Madrid} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN};echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly-net

volumes:
   firefly_iii_upload:

networks:
  firefly-net:
    external: true # Defined in databases 
  firefly-net-frontend:
    external: true # Defined in databases
  firefly-db-net:
    external: true # Defined in databases
