volumes:
  ts_vaultwarden:

services:
  vaultwarden:
    image: ghcr.io/chukysoria/vaultwarden:v0.1.1
    networks:
      - frontend
    volumes:
      - ts_vaultwarden:/tsconfig
      - /volume1/docker/vaultwarden:/app/vw/data:rw
    environment:
      PUID: 1027
      PGID: 100
      TZ: Europe/Madrid   
      DOCKER_MODS: 'ghcr.io/chukysoria/tailscale-mod:v1.1.3'
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_FUNNEL: 1
      TAILSCALE_USE_SSH: 1
      TAILSCALE_STATE_DIR: /tsconfig
      TAILSCALE_HOSTNAME: vw
      TAILSCALE_SERVE_PORT: 7979
      ROCKET_PORT: 7979
    ports:
      - 7979:7979
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vw.boulebar.duckdns.org`)"

networks:
  frontend:
    external: true