---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0.10514-ls314@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438
    volumes:
      - ${BASE_PATH:-/volume2/docker/}radarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-radarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.radarr-rtr.rule: Host(`radarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.radarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19.2979-ls323@sha256:4d9df314875e1249ab7d6170c2b9b3dc1d8e6383f168ceb10dc9a5ad9b324739
    volumes:
      - ${BASE_PATH:-/volume2/docker/}sonarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-rtr.rule: Host(`sonarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.sonarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:v1.6.0-ls362@sha256:a20fb11a440d704a9d61c283aa26462aad33dc63223b173f8d8c77d33e8e9d59
    volumes:
      - ${BASE_PATH:-/volume2/docker/}bazarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video/Series:/media/video/Series
      - /volume2/video/Pelis:/media/video/Pelis
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr-rtr.rule: Host(`bazarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.bazarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.5.2.5491-ls158@sha256:91844fa2c927ad6ede5630127183cc7868b175f6223e83e6a5da1fffea2aa782
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}prowlarr:/config:rw
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr-rtr.rule: Host(`prowlarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.prowlarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls40@sha256:c74c32408fdf6e7926ad62641fc1a5544206ee65c33f2188bb179edb30e28f5a
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}lidarr:/config
      - /volume2/video/torrents/:/downloads
      - /volume2/music:/media/music
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-lidarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr-rtr.rule: Host(`lidarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.lidarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  whisparr:
    image: ghcr.io/hotio/whisparr:v3-3.0.2.1433@sha256:51d3b0b952a0a502ba052704327adbf8885dd02fd39ff9aa434ed63609c75f4f
    networks:
      - frontend
    environment:
      # Common variables
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      UMASK: 002
    volumes:
      - ${BASE_PATH:-/volume2/docker/}whisparr:/config:rw
      - /volume2/video:/media/video
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr-rtr.rule: Host(`whisparr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.whisparr-rtr.middlewares: authentik@docker
    restart: unless-stopped

networks:
  frontend:
    external: true # Defined in Portainer
