---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1.10360-ls299@sha256:6f1dda18354ea7f28cead8f6d099fc8222498c3ae165f567d504ed04d70980d7
    volumes:
      - ${BASE_PATH:-/volume2/docker/}radarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-radarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.radarr-rtr.rule: Host(`radarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.radarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  sonarr:
    image: ghcr.io/chukysoria/sonarr:v0.5.24@sha256:09d47e450f463a20b6793f87ca373d442c97a4dfe4346386c8280df0ee3f39c6
    volumes:
      - ${BASE_PATH:-/volume2/docker/}sonarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-rtr.rule: Host(`sonarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.sonarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  bazarr:
    image: ghcr.io/chukysoria/bazarr:v0.8.30@sha256:9b09f9fe82306899636d50b2446a76e99401f961f707fc9357b600ad00454bb6
    volumes:
      - ${BASE_PATH:-/volume2/docker/}bazarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video/Series:/media/video/Series
      - /volume2/video/Pelis:/media/video/Pelis
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr-rtr.rule: Host(`bazarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.bazarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/chukysoria/prowlarr:v0.9.37@sha256:52fd6c940b66931f16ba35edcd3ec71996d57c9c11997a0149095e435196c497
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}prowlarr:/config:rw
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr-rtr.rule: Host(`prowlarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.prowlarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls24@sha256:a11272d4ff510a3665e37e11573c7f4ed134ba8089e54baf4c4f916d2e87febc
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}lidarr:/config
      - /volume2/video/torrents/:/downloads
      - /volume2/music:/media/music
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-lidarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr-rtr.rule: Host(`lidarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.lidarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  whisparr:
    image: ghcr.io/hotio/whisparr:v3-3.0.2.1433@sha256:51d3b0b952a0a502ba052704327adbf8885dd02fd39ff9aa434ed63609c75f4f
    networks:
      - frontend
    environment:
      # Common variables
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      UMASK: 002
    volumes:
      - ${BASE_PATH:-/volume2/docker/}whisparr:/config:rw
      - /volume2/video:/media/video
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr-rtr.rule: Host(`whisparr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.whisparr-rtr.middlewares: authentik@docker
    restart: unless-stopped

networks:
  frontend:
    external: true # Defined in Portainer
