---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1.10360-ls297@sha256:581f159c2b67436863cb4da30e158ef6f6b8878472abbba79ee5d5f7e6b7d28d
    volumes:
      - ${BASE_PATH:-/volume2/docker/}radarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-radarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.radarr-rtr.rule: Host(`radarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.radarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  sonarr:
    image: ghcr.io/chukysoria/sonarr:v0.5.24@sha256:09d47e450f463a20b6793f87ca373d442c97a4dfe4346386c8280df0ee3f39c6
    volumes:
      - ${BASE_PATH:-/volume2/docker/}sonarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video:/media/video
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-rtr.rule: Host(`sonarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.sonarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  bazarr:
    image: ghcr.io/chukysoria/bazarr:v0.8.29@sha256:9ccdd8405a10d2a360dcb99d1d790df9f3c61f7f31e54c526f13bce329dd5169
    volumes:
      - ${BASE_PATH:-/volume2/docker/}bazarr:/config:rw
      - /volume2/downloads:/media/downloads
      - /volume2/video/Series:/media/video/Series
      - /volume2/video/Pelis:/media/video/Pelis
    networks:
      - frontend
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr-rtr.rule: Host(`bazarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.bazarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/chukysoria/prowlarr:v0.9.36@sha256:2df8191afb9eb673c64f33347c65fbad02793ae5de2b4e1eff1ebd3f9e82b4c5
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}prowlarr:/config:rw
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr-rtr.rule: Host(`prowlarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.prowlarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls22@sha256:dbffcf91da47d48e09e613857032c95a62755b928a71a7718688e3ab03fbbd26
    networks:
      - frontend
    volumes:
      - ${BASE_PATH:-/volume2/docker/}lidarr:/config
      - /volume2/video/torrents/:/downloads
      - /volume2/music:/media/music
    healthcheck:
      test: ["CMD", "/etc/s6-overlay/s6-rc.d/svc-lidarr/data/check"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr-rtr.rule: Host(`lidarr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.lidarr-rtr.middlewares: authentik@docker
    restart: unless-stopped

  whisparr:
    image: ghcr.io/hotio/whisparr:v3-3.0.2.1433@sha256:51d3b0b952a0a502ba052704327adbf8885dd02fd39ff9aa434ed63609c75f4f
    networks:
      - frontend
    environment:
      # Common variables
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      UMASK: 002
    volumes:
      - ${BASE_PATH:-/volume2/docker/}whisparr:/config:rw
      - /volume2/video:/media/video
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr-rtr.rule: Host(`whisparr.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.whisparr-rtr.middlewares: authentik@docker
    restart: unless-stopped

networks:
  frontend:
    external: true # Defined in Portainer
