---
volumes:
  ts_hass:

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2023.12.3-ls212
    environment:
      PUID: 1029
      PGID: 65536
      TZ: Europe/Madrid
      DOCKER_MODS: "ghcr.io/chukysoria/tailscale-mod:v1.1.3|linuxserver/mods:homeassistant-hacs|linuxserver/mods:universal-package-install"
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_STATE_DIR: /tsconfig
      TAILSCALE_HOSTNAME: ha
      TAILSCALE_SERVE_PORT: 8123
      TAILSCALE_FUNNEL: 1
      INSTALL_PACKAGES: nmap
    volumes:
      - /volume2/docker/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - ts_hass:/tsconfig
    network_mode: host
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.rule=Host(`ha.boulebar.duckdns.org`)"
      - "traefik.http.routers.ha.service=svc-ha"
      - "traefik.http.routers.ha.middlewares=csp-homeassistant@file"
      - "traefik.http.services.svc-ha.loadbalancer.server.port=8123"
