---
volumes:
  ts_hass:

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2024.1.1-ls218
    container_name: homeassistant
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      DOCKER_MODS: "ghcr.io/chukysoria/tailscale-mod:v1.1.3|linuxserver/mods:homeassistant-hacs|linuxserver/mods:universal-package-install"
      # Tailscale
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY:?Tailscale Authorization key}
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_STATE_DIR: /tsconfig
      TAILSCALE_HOSTNAME: ha
      TAILSCALE_SERVE_PORT: 8123
      TAILSCALE_FUNNEL: 1
      # Packages
      INSTALL_PACKAGES: nmap
    volumes:
      - ${BASE_PATH:-/volume2/docker/}hass:/config
      - /etc/localtime:/etc/localtime:ro
      - ts_hass:/tsconfig
    networks:
      frontend:
      homeassistant:
      macvlan:
        ipv4_address: 192.168.1.51
    restart: unless-stopped
    labels:
      traefik.enable: true
      # Routers
      #traefik.http.routers.ha-rtr.rule: Host(`ha.${DOMAIN:-boulebar.duckdns.org}`)
      #traefik.http.routers.ha-rtr.service: ha-svc

      traefik.http.routers.ha-passthrough-rtr.rule: Host(`ha.${DOMAIN:-boulebar.duckdns.org}`) && !( (PathPrefix(`/auth/`)) && !(PathPrefix(`/auth/token`)) ) && !(PathPrefix(`/outpost.goauthentik.io/`))
      traefik.http.routers.ha-passthrough-rtr.service: ha-svc

      traefik.http.routers.ha-auth-rtr.rule: Host(`ha.${DOMAIN:-boulebar.duckdns.org}`) && ( (PathPrefix(`/auth/`)) && !(PathPrefix(`/auth/token`)) )
      traefik.http.routers.ha-auth-rtr.service: ha-svc

      # Middlewares
      #traefik.http.routers.ha-rtr.middlewares: csp-homeassistant@file
      traefik.http.routers.ha-passthrough-rtr.middlewares: csp-homeassistant@file
      traefik.http.routers.ha-auth-rtr.middlewares: csp-homeassistant@file,authentik@docker
      
      # Services
      traefik.http.services.ha-svc.loadbalancer.server.port: 8123

networks:
  frontend:
    external: true # Defined in portainer
  macvlan:
    external: true # Defined in Adguard
  homeassistant:
    external: true # Defined in database
  