---
volumes:
  ts_code-server:

services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.99.4-ls269@sha256:fc486df00cbbc833854d997554832ceadefbab8f41d4e39f10fcfbd7966fffbd
    environment:
      # General LinuxServer.io
      PUID: ${PUID:-1029}
      PGID: ${PGID:-65536}
      TZ: ${TZ:-Europe/Madrid}
      DOCKER_MODS: "ghcr.io/chukysoria/tailscale-mod:v1.1.5|linuxserver/mods:universal-docker|linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-extension-arguments|linuxserver/mods:universal-package-install|ghcr.io/chukysoria/docker-mod-code-server:v0.1.0"
      # Tailscale
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY:?Tailscale Authorization key}
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_STATE_DIR: /tsconfig
      TAILSCALE_HOSTNAME: vscode
      TAILSCALE_SERVE_PORT: 8443
      # Code Server
      DEFAULT_WORKSPACE: ${BASE_PATH:-/volume2/docker/}hass
      CS_DISABLE_GETTING_STARTED_OVERRIDE: true
      SUDO_PASSWORD: abc
      VSCODE_EXTENSION_IDS: "keesschollaart.vscode-home-assistant|ms-azuretools.vscode-docker|redhat.vscode-yaml|lukas-tr.materialdesignicons-intellisense|tailscale.vscode-tailscale|ms-vscode-remote.vscode-remote-extensionpack"
      INSTALL_PACKAGES: wget
      EXTENSIONS_GALLERY: '{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery","itemUrl": "https://marketplace.visualstudio.com/items"}'
    volumes:
      - ${BASE_PATH:-/volume2/docker/}codeserver:/config
      - ${BASE_PATH:-/volume2/docker/}:${BASE_PATH:-/volume2/docker/}
      - ts_code-server:/tsconfig
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.vscode-rtr.rule: Host(`vscode.${DOMAIN:-boulebar.duckdns.org}`)
      traefik.http.routers.vscode-rtr.middlewares: authentik@docker
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8443"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
      # start_interval: 5s

networks:
  frontend:
    external: true # Defined in databases
