---
   
name: Sync labels
            
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:
                                                                                            
                                                                                                  
jobs:
  labels:
    name: ♻️ Sync labels
    uses: chukysoria/workflows/.github/workflows/labels.yml@9b1c843ea56815ffcc5b0e975cc1dac811fef922 # v1.1.39
                                                                                                                            
