---
   
name: Sync labels
            
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:
                                                                                            
                                                                                                  
jobs:
  labels:
    name: ♻️ Sync labels
    uses: chukysoria/workflows/.github/workflows/labels.yml@c06ad64aea96e53c39f958574bb782fd479c9039 # v1.1.36
                                                                                                                            
