---
   
name: Sync labels
            
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:
                                                                                            
                                                                                                  
jobs:
  labels:
    name: ♻️ Sync labels
    uses: chukysoria/workflows/.github/workflows/labels.yml@587e6a91fc74c2f8c415a6dbf2934ce164b1c300 # v1.1.37
                                                                                                                            
